name: Deploy Docs Microsite

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Who triggered this test run?'
  push:
    branches:
      - master
    paths:
      - 'src/main/**'

jobs:
  deploy-docs-microsite:
    name: Build and Deploy Docs microsite to treasure-data.github.io/td-android-sdk
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup
        continue-on-error: true
        run: |
          sudo apt update
          apt-get -y install default-jdk
          apt-get -y install android-sdk
          apt-get -y install gradle
          export ANDROID_SDK_ROOT='/usr/lib/android-sdk'
          apt-get -y install unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip -o commandlinetools-linux-6609375_latest.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$PATH
          yes | sudo /usr/lib/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses

      - name: git checkout
        uses: actions/checkout@v2
        with:
          persistent-creadentials: false
          fetch-depth: 0
          repository: 'blackstoneengineering/td-android-sdk'
          ref: 'master'
          path: td-android-sdk
      # - name: git checkout - debug
      #   run: |
      #     git clone https://github.com/blackstoneengineering/td-android-sdk td-android-sdk
      #     cd td-android-sdk
      #     git checkout master
      - name: build docs
        continue-on-error: true
        run: |
          export ANDROID_SDK_ROOT='/usr/lib/android-sdk'
          cd td-android-sdk
          ./gradlew javadocJar
      - name: clean docs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: td-android-sdk/build/docs/javadoc
      - name: Commit Docs
        run: |
          mv -f td-android-sdk/build/docs/javadoc ./docs
          cd td-android-sdk
          git config user.email "ci-bot@treasure-data.com"
          git config user.name "ci-bot"
          git stash
          git reset --hard
          git fetch
          git checkout gh-pages
          git pull
          rm -rf ./docs
          mv ../docs ./docs
          git add ./docs/*
          git commit -m "[ci-bot] Updating docs microsite to latest from master"
      - name: deploy docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
