name: Deploy Docs Microsite

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Who triggered this test run?'
  push:
    branches:
      - master
    paths:
      - 'src/main/**'

jobs:
  deploy-docs-microsite:
    name: Build and Deploy Docs microsite to treasure-data.github.io/td-android-sdk
    runs-on: ubuntu-latest
    steps:
      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
      - name: git checkout
        uses: actions/checkout@v2
        with:
          persistent-creadentials: false
          fetch-depth: 0
          repository: 'blackstoneengineering/td-android-sdk'
          ref: 'master'
          path: td-android-sdk
      # - name: git checkout - debug
      #   run: |
      #     git clone https://github.com/blackstoneengineering/td-android-sdk td-android-sdk
      #     cd td-android-sdk
      #     git checkout master
      - name: Build docs
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: javadocSite
      # - name: gradle build
      #   run: ./gradlew javadocJar
      # - name: build docs
      #   run: |
      #     ls
      #     pwd
      #     javadoc -d docs ./src/main/java/com/treasuredata/android/*.java
      # - name: build docs
      #   run: |
      #     ls
      #     pwd
      #     cd td-android-sdk
      #     ./gradelw javadocSite
      - name: clean docs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: docs
      # - name: deploy docs
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
